# Generated by Django 4.1.7 on 2023-04-11 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listas',
            new_name='Lista',
        ),
    ]
