# Generated by Django 4.1.7 on 2023-04-12 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0002_rename_listas_lista'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lista',
            old_name='produto',
            new_name='nome',
        ),
    ]
