# Generated by Django 4.1.7 on 2023-04-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0003_rename_produto_lista_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='preco',
            field=models.IntegerField(default=0, verbose_name=0),
            preserve_default=False,
        ),
    ]
