# Generated by Django 4.1.7 on 2023-04-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0004_lista_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='preco',
            field=models.IntegerField(),
        ),
    ]
