# Generated by Django 4.1.7 on 2023-04-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0005_alter_lista_preco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=64)),
                ('preco', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='lista',
            old_name='nome',
            new_name='nome_lista',
        ),
        migrations.RemoveField(
            model_name='lista',
            name='preco',
        ),
    ]
