# Generated by Django 4.1.7 on 2023-04-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0007_produto_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='nome',
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.FloatField(),
        ),
        migrations.AddField(
            model_name='produto',
            name='nome',
            field=models.ManyToManyField(blank=True, related_name='nome', to='listas.lista'),
        ),
    ]
